import Fee from "../models/feeModel.js";
import Student from "../models/studentsModel.js";
import Class from "../models/classModel.js";
import Finance from "../models/financeModel.js";

// Helper: ensure monthly finance exists
async function getOrCreateMonthlyFinance(month, year) {
  let finance = await Finance.findOne({ month, year });
  if (!finance) {
    finance = new Finance({
      date: new Date(year, month - 1, 1),
      income: 0,
      expenses: 0,
      debt: 0,
      month,
      year,
      isAutoGenerated: false,
      paidFeesCount: 0,
      paidSalariesCount: 0,
      unpaidFeesCount: 0,
      lastUpdated: new Date()
    });
    await finance.save();
  }
  return finance;
}

// Create fee record for a student
export const createFeeRecord = async (req, res) => {
  try {
    const { student, amount, month, year, dueDate, note, paid, paidDate } = req.body;

    if (!student || !amount || !month || !year || !dueDate) {
      return res.status(400).json({ message: "Fadlan buuxi dhammaan meelaha banan" });
    }

    // Check if student exists and get their class
    const existingStudent = await Student.findById(student).populate('class');
    if (!existingStudent) {
      return res.status(404).json({ message: "Ardayga lama helin" });
    }

    if (!existingStudent.class) {
      return res.status(400).json({ message: "Ardaygan fasalka lama geeyey" });
    }

    // Check if fee record already exists for this student, month, and year
    const existingFee = await Fee.findOne({ student, month, year });
    if (existingFee) {
      return res.status(400).json({ message: "Lacagta bishan ardaygan horay ayaa loo abuuray" });
    }

    const feeRecord = new Fee({
      student,
      class: existingStudent.class._id,
      amount,
      month,
      year,
      dueDate: new Date(dueDate),
      note: note || "",
      createdBy: req.user.id,
      paid: !!paid,
      paidDate: paid ? (paidDate ? new Date(paidDate) : new Date()) : null
    });

    await feeRecord.save();

    // Real-time Finance update
    const finance = await getOrCreateMonthlyFinance(parseInt(month), parseInt(year));
    if (feeRecord.paid) {
      finance.income = Math.max(0, (finance.income || 0) + feeRecord.amount);
      finance.paidFeesCount = (finance.paidFeesCount || 0) + 1;
    } else {
      finance.debt = Math.max(0, (finance.debt || 0) + feeRecord.amount);
      finance.unpaidFeesCount = (finance.unpaidFeesCount || 0) + 1;
    }
    finance.lastUpdated = new Date();
    await finance.save();

    // Populate the created record for response
    await feeRecord.populate(['student', 'class', 'createdBy']);

    return res.status(201).json({ 
      message: "Diiwaanka lacagta si guul leh ayaa loo abuuray", 
      feeRecord 
    });

  } catch (error) {
    console.error("Error creating fee record:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay diiwaanka lacagta abuurista" });
  }
};

// Create fees for all students in a class
export const createClassFees = async (req, res) => {
  try {
    const { classId, amount, month, year, dueDate, note, paid } = req.body;

    if (!classId || !amount || !month || !year || !dueDate) {
      return res.status(400).json({ message: "Fadlan buuxi dhammaan meelaha banan" });
    }

    // Check if class exists
    const existingClass = await Class.findById(classId);
    if (!existingClass) {
      return res.status(404).json({ message: "Fasalka lama helin" });
    }

    // Get all students in the class
    const students = await Student.find({ class: classId });
    if (students.length === 0) {
      return res.status(400).json({ message: "Fasalkan ardayga kuma jiraan" });
    }

    const feeRecords = [];
    const existingFees = [];

    let createdPaidTotal = 0;
    let createdUnpaidTotal = 0;

    for (const student of students) {
      // Check if fee already exists for this student
      const existingFee = await Fee.findOne({ 
        student: student._id, 
        month, 
        year 
      });

      if (existingFee) {
        existingFees.push(student.fullname);
        continue;
      }

      const feeRecord = new Fee({
        student: student._id,
        class: classId,
        amount,
        month,
        year,
        dueDate: new Date(dueDate),
        note: note || "",
        createdBy: req.user.id,
        paid: !!paid,
        paidDate: paid ? new Date() : null
      });

      await feeRecord.save();
      feeRecords.push(feeRecord);

      if (feeRecord.paid) createdPaidTotal += amount; else createdUnpaidTotal += amount;
    }

    // Real-time Finance update once
    if (feeRecords.length > 0) {
      const finance = await getOrCreateMonthlyFinance(parseInt(month), parseInt(year));
      if (createdPaidTotal > 0) {
        finance.income = Math.max(0, (finance.income || 0) + createdPaidTotal);
        finance.paidFeesCount = (finance.paidFeesCount || 0) + feeRecords.filter(f => f.paid).length;
      }
      if (createdUnpaidTotal > 0) {
        finance.debt = Math.max(0, (finance.debt || 0) + createdUnpaidTotal);
        finance.unpaidFeesCount = (finance.unpaidFeesCount || 0) + feeRecords.filter(f => !f.paid).length;
      }
      finance.lastUpdated = new Date();
      await finance.save();
    }

    let message = `${feeRecords.length} diiwaanka lacagta si guul leh ayaa loo abuuray`;
    if (existingFees.length > 0) {
      message += `. ${existingFees.length} ardayga horay ayaa lacagtooda la abuuray: ${existingFees.join(', ')}`;
    }

    return res.status(201).json({ 
      message, 
      created: feeRecords.length,
      existing: existingFees.length,
      feeRecords 
    });

  } catch (error) {
    console.error("Error creating class fees:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay lacagta fasalka abuurista" });
  }
};

// Get students by class for fee management
export const getStudentsByClass = async (req, res) => {
  try {
    const { classId } = req.params;
    const { month, year } = req.query;

    if (!classId) {
      return res.status(400).json({ message: "Fadlan dooro fasalka" });
    }

    // Check if class exists
    const existingClass = await Class.findById(classId);
    if (!existingClass) {
      return res.status(404).json({ message: "Fasalka lama helin" });
    }

    const students = await Student.find({ class: classId })
      .populate('class')
      .sort({ fullname: 1 });

    if (students.length === 0) {
      return res.status(404).json({ message: "Fasalkan ardayga kuma jiraan" });
    }

    // Always get fee records if month and year are provided, or return students without fee records
    let studentsWithFees = await Promise.all(
      students.map(async (student) => {
        let feeRecord = null;
        
        if (month && year) {
          feeRecord = await Fee.findOne({
            student: student._id,
            month: parseInt(month),
            year: parseInt(year)
          });
        }

        return {
          ...student.toObject(),
          feeRecord
        };
      })
    );

    return res.status(200).json({ 
      message: "Ardayda si guul leh ayaa loo helay", 
      students: studentsWithFees 
    });

  } catch (error) {
    console.error("Error getting students by class:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay ardayda soo bandhigista" });
  }
};

// Get all fee records
export const getAllFeeRecords = async (req, res) => {
  try {
    const { month, year, classId, paid } = req.query;
    
    let filter = {};
    if (month) filter.month = parseInt(month);
    if (year) filter.year = parseInt(year);
    if (classId) filter.class = classId;
    if (paid !== undefined) filter.paid = paid === 'true';

    const feeRecords = await Fee.find(filter)
      .populate('student', 'fullname')
      .populate('class', 'name')
      .populate('createdBy', 'username')
      .sort({ createdAt: -1 });

    return res.status(200).json({ 
      message: "Diiwaanka lacagta si guul leh ayaa loo helay", 
      feeRecords 
    });

  } catch (error) {
    console.error("Error getting fee records:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay diiwaanka lacagta soo bandhigista" });
  }
};

// Get fee records for a specific student
export const getStudentFeeRecords = async (req, res) => {
  try {
    const { studentId } = req.params;
    const { year } = req.query;

    let filter = { student: studentId };
    if (year) filter.year = parseInt(year);

    const feeRecords = await Fee.find(filter)
      .populate('student', 'fullname')
      .populate('class', 'name')
      .populate('createdBy', 'username')
      .sort({ year: -1, month: -1 });

    return res.status(200).json({ 
      message: "Diiwaanka lacagta ardayga si guul leh ayaa loo helay", 
      feeRecords 
    });

  } catch (error) {
    console.error("Error getting student fee records:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay diiwaanka lacagta ardayga soo bandhigista" });
  }
};

// Update fee record (mark as paid/unpaid)
export const updateFeeRecord = async (req, res) => {
  try {
    const { feeId } = req.params;
    const { paid, paidDate, note, amount, dueDate } = req.body;

    const feeRecord = await Fee.findById(feeId);
    if (!feeRecord) {
      return res.status(404).json({ message: "Diiwaanka lacagta lama helin" });
    }

    const prevPaid = !!feeRecord.paid;
    const prevAmount = Number(feeRecord.amount || 0);

    // Update fields
    if (paid !== undefined) {
      feeRecord.paid = paid;
      feeRecord.paidDate = paid ? (paidDate ? new Date(paidDate) : new Date()) : null;
    }
    if (note !== undefined) feeRecord.note = note;
    if (amount !== undefined && !isNaN(amount)) feeRecord.amount = Number(amount);
    if (dueDate !== undefined) feeRecord.dueDate = new Date(dueDate);

    await feeRecord.save();

    // Real-time Finance adjustment
    const finance = await getOrCreateMonthlyFinance(feeRecord.month, feeRecord.year);

    const newPaid = !!feeRecord.paid;
    const newAmount = Number(feeRecord.amount || 0);

    // Case 1: Status changed
    if (prevPaid !== newPaid) {
      if (newPaid) {
        // Moved from unpaid to paid
        finance.income = Math.max(0, (finance.income || 0) + newAmount);
        finance.debt = Math.max(0, (finance.debt || 0) - prevAmount);
        finance.paidFeesCount = (finance.paidFeesCount || 0) + 1;
        finance.unpaidFeesCount = Math.max(0, (finance.unpaidFeesCount || 0) - 1);
      } else {
        // Moved from paid to unpaid
        finance.income = Math.max(0, (finance.income || 0) - prevAmount);
        finance.debt = Math.max(0, (finance.debt || 0) + newAmount);
        finance.paidFeesCount = Math.max(0, (finance.paidFeesCount || 0) - 1);
        finance.unpaidFeesCount = (finance.unpaidFeesCount || 0) + 1;
      }
    } else {
      // Case 2: Status same, amount changed
      const delta = newAmount - prevAmount;
      if (delta !== 0) {
        if (newPaid) {
          finance.income = Math.max(0, (finance.income || 0) + delta);
        } else {
          finance.debt = Math.max(0, (finance.debt || 0) + delta);
        }
      }
    }

    finance.lastUpdated = new Date();
    await finance.save();

    // Populate for response
    await feeRecord.populate(['student', 'class', 'createdBy']);

    return res.status(200).json({ 
      message: "Diiwaanka lacagta si guul leh ayaa loo cusboonaysiiyay", 
      feeRecord 
    });

  } catch (error) {
    console.error("Error updating fee record:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay diiwaanka lacagta cusboonaysiinta" });
  }
};

// Delete fee record
export const deleteFeeRecord = async (req, res) => {
  try {
    const { feeId } = req.params;

    const feeRecord = await Fee.findById(feeId);
    if (!feeRecord) {
      return res.status(404).json({ message: "Diiwaanka lacagta lama helin" });
    }

    // Adjust finance before delete
    const finance = await getOrCreateMonthlyFinance(feeRecord.month, feeRecord.year);
    if (feeRecord.paid) {
      finance.income = Math.max(0, (finance.income || 0) - (feeRecord.amount || 0));
      finance.paidFeesCount = Math.max(0, (finance.paidFeesCount || 0) - 1);
    } else {
      finance.debt = Math.max(0, (finance.debt || 0) - (feeRecord.amount || 0));
      finance.unpaidFeesCount = Math.max(0, (finance.unpaidFeesCount || 0) - 1);
    }
    finance.lastUpdated = new Date();
    await finance.save();

    await Fee.findByIdAndDelete(feeId);

    return res.status(200).json({ 
      message: "Diiwaanka lacagta si guul leh ayaa loo tirtay" 
    });

  } catch (error) {
    console.error("Error deleting fee record:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay diiwaanka lacagta tirista" });
  }
};

// Get fee statistics
export const getFeeStatistics = async (req, res) => {
  try {
    const { month, year } = req.query;
    
    let filter = {};
    if (month) filter.month = parseInt(month);
    if (year) filter.year = parseInt(year);

    const totalFees = await Fee.countDocuments(filter);
    const paidFees = await Fee.countDocuments({ ...filter, paid: true });
    const unpaidFees = totalFees - paidFees;
    
    const totalAmount = await Fee.aggregate([
      { $match: filter },
      { $group: { _id: null, total: { $sum: "$amount" } } }
    ]);

    const paidAmount = await Fee.aggregate([
      { $match: { ...filter, paid: true } },
      { $group: { _id: null, total: { $sum: "$amount" } } }
    ]);

    return res.status(200).json({
      message: "Tirakoobka lacagta si guul leh ayaa loo helay",
      statistics: {
        totalFees,
        paidFees,
        unpaidFees,
        totalAmount: totalAmount[0]?.total || 0,
        paidAmount: paidAmount[0]?.total || 0,
        unpaidAmount: (totalAmount[0]?.total || 0) - (paidAmount[0]?.total || 0)
      }
    });

  } catch (error) {
    console.error("Error getting fee statistics:", error);
    return res.status(500).json({ message: "Khalad ayaa dhacay tirakoobka lacagta soo bandhigista" });
  }
};