import Finance from "../models/financeModel.js";
import Fee from "../models/feeModel.js";
import Salary from "../models/salaryModel.js";
import FamilyFee from "../models/familyFeeModel.js";

const getPaidFeeMatch = (isPaid) => ({
  $or: [
    { paid: isPaid },
    { paid: isPaid ? 1 : 0 },
    { paid: String(isPaid) }
  ]
});

export const AddFinance = async ( req, res ) => {
  try {

    const { income , expenses , debt  , date } = req.body;

    if (!income || !expenses || !debt || !date) {
      return res.status(400).json({ message: "Fadlan buuxi dhammaan meelaha banan" });
    }

    


    const dt = date ? new Date(date) : new Date();
    const monthNum = dt.getMonth() + 1;
    const yearNum = dt.getFullYear();

    const finance = new Finance({
      income,
      expenses,
      debt,
      date: dt,
      month: monthNum,
      year: yearNum,
      isAutoGenerated: false
    });


    await finance.save();

    return res.status(201).json({ message: "Maalgelinta si guul leh ayaa loo abuuray", finance });
  } catch (error) {
    console.error("error in AddFinance function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

// Auto-generate monthly finance summary
export const generateMonthlyFinance = async (req, res) => {
  try {
    const { month, year } = req.body;
    
    if (!month || !year) {
      return res.status(400).json({ message: "Fadlan buuxi bisha iyo sanadka" });
    }

    const monthNum = parseInt(month);
    const yearNum = parseInt(year);

    // Calculate total student fees (income) for the month
    const studentFeesResult = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum,
          $or: [{ paid: true }, { paid: 1 }, { paid: 'true' }] 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    const totalIncome = studentFeesResult.length > 0 ? studentFeesResult[0].total : 0;
    const paidFeesCount = studentFeesResult.length > 0 ? studentFeesResult[0].count : 0;

    // Calculate total teacher salaries (expenses) for the month
    const salaryExpensesResult = await Salary.aggregate([
      { 
        $match: { month: monthNum, year: yearNum } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$totalAmount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    const paidSalariesResult = await Salary.aggregate([
      { 
        $match: { month: monthNum, year: yearNum, paid: true } 
      },
      { 
        $group: { 
          _id: null, 
          count: { $sum: 1 }
        } 
      }
    ]);

    const totalExpenses = salaryExpensesResult.length > 0 ? salaryExpensesResult[0].total : 0;
    const paidSalariesCount = paidSalariesResult.length > 0 ? paidSalariesResult[0].count : 0;

    // Calculate unpaid fees (debt)
    const unpaidFeesResult = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum,
          $or: [{ paid: false }, { paid: 0 }, { paid: 'false' }] 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    const totalDebt = unpaidFeesResult.length > 0 ? unpaidFeesResult[0].total : 0;
    const unpaidFeesCount = unpaidFeesResult.length > 0 ? unpaidFeesResult[0].count : 0;

    // Check if finance record already exists for this month
    const existingFinance = await Finance.findOne({
      month: monthNum,
      year: yearNum
    });

    if (existingFinance) {
      // Update existing record
      existingFinance.income = totalIncome;
      existingFinance.expenses = totalExpenses;
      existingFinance.debt = totalDebt;
      existingFinance.paidFeesCount = paidFeesCount;
      existingFinance.paidSalariesCount = paidSalariesCount;
      existingFinance.unpaidFeesCount = unpaidFeesCount;
      existingFinance.lastUpdated = new Date();
      
      await existingFinance.save();
      
      return res.status(200).json({ 
        message: "Maalgelinta bishan si guul leh ayaa loo cusboonaysiiyay", 
        finance: existingFinance 
      });
    } else {
      // Create new finance record
      const finance = new Finance({
        income: totalIncome,
        expenses: totalExpenses,
        debt: totalDebt,
        month: monthNum,
        year: yearNum,
        paidFeesCount,
        paidSalariesCount,
        unpaidFeesCount,
        date: new Date(yearNum, monthNum - 1, 1),
        isAutoGenerated: true
      });

      await finance.save();

      return res.status(201).json({ 
        message: "Maalgelinta bishan si guul leh ayaa loo abuuray", 
        finance 
      });
    }
  } catch (error) {
    console.error("error in generateMonthlyFinance function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

export const getAllFinance = async ( req, res ) => {
  try {
    const finance = await Finance.find({}).sort({ createdAt: -1 });

    return res.status(200).json({ message: "Maalgelinta si guul leh ayaa loo helay", finance });
  } catch (error) {
    console.error("error in getAllFinance function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

// Get finance summary with detailed breakdown
export const getFinanceSummary = async (req, res) => {
  try {
    const { month, year } = req.query;
    
    if (!month || !year) {
      return res.status(400).json({ message: "Fadlan dooro bisha iyo sanadka" });
    }

    const monthNum = parseInt(month);
    const yearNum = parseInt(year);

    // Get total student fees for the month (income)
    const studentFeesTotal = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum,
          $or: [{ paid: true }, { paid: 1 }, { paid: 'true' }] 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    // Get total teacher salaries for the month (expenses)
    const teacherSalariesTotal = await Salary.aggregate([
      { 
        $match: { month: monthNum, year: yearNum } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$totalAmount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    const paidSalariesTotal = await Salary.aggregate([
      { 
        $match: { month: monthNum, year: yearNum, paid: true } 
      },
      { 
        $group: { 
          _id: null, 
          count: { $sum: 1 }
        } 
      }
    ]);

    // Get unpaid fees (debt)
    const unpaidFeesTotal = await Fee.aggregate([
      { 
        $match: { 
          month: monthNum, 
          year: yearNum,
          $or: [{ paid: false }, { paid: 0 }, { paid: 'false' }] 
        } 
      },
      { 
        $group: { 
          _id: null, 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      }
    ]);

    // Get manual finance records for the month
    const startDate = new Date(yearNum, monthNum - 1, 1);
    const endDate = new Date(yearNum, monthNum, 0);
    
    const manualFinance = await Finance.find({
      date: { $gte: startDate, $lte: endDate },
      isAutoGenerated: { $ne: true }
    }).sort({ createdAt: -1 });

    // Get auto-generated finance record for the month
    const autoFinance = await Finance.findOne({
      month: monthNum,
      year: yearNum,
      isAutoGenerated: true
    });

    const summary = {
      month: monthNum,
      year: yearNum,
      income: studentFeesTotal.length > 0 ? studentFeesTotal[0].total : 0,
      expenses: teacherSalariesTotal.length > 0 ? teacherSalariesTotal[0].total : 0,
      debt: unpaidFeesTotal.length > 0 ? unpaidFeesTotal[0].total : 0,
      paidFeesCount: studentFeesTotal.length > 0 ? studentFeesTotal[0].count : 0,
      paidSalariesCount: paidSalariesTotal.length > 0 ? paidSalariesTotal[0].count : 0,
      unpaidFeesCount: unpaidFeesTotal.length > 0 ? unpaidFeesTotal[0].count : 0,
      manualFinance,
      autoFinance,
      netProfit: (studentFeesTotal.length > 0 ? studentFeesTotal[0].total : 0) - 
                 (teacherSalariesTotal.length > 0 ? teacherSalariesTotal[0].total : 0)
    };

    return res.status(200).json({ 
      message: "Faahfaahinta maalgelinta si guul leh ayaa loo helay", 
      summary: { ...summary, manualFinance, autoFinance }
    });
  } catch (error) {
    console.error("error in getFinanceSummary function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

// Get monthly breakdown for the entire year
export const getYearlyFinanceBreakdown = async (req, res) => {
  try {
    const { year } = req.query;
    
    if (!year) {
      return res.status(400).json({ message: "Fadlan dooro sanadka" });
    }

    const yearNum = parseInt(year);

    // Get monthly breakdown of student fees
    const monthlyFees = await Fee.aggregate([
      { 
        $match: { 
          year: yearNum,
          $or: [{ paid: true }, { paid: 1 }, { paid: 'true' }] 
        } 
      },
      { 
        $group: { 
          _id: "$month", 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Get monthly breakdown of teacher salary expenses
    const monthlySalaryExpenses = await Salary.aggregate([
      { 
        $match: { year: yearNum } 
      },
      { 
        $group: { 
          _id: "$month", 
          total: { $sum: "$totalAmount" },
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Get monthly breakdown of paid teacher salaries
    const monthlyPaidSalaries = await Salary.aggregate([
      { 
        $match: { year: yearNum, paid: true } 
      },
      { 
        $group: { 
          _id: "$month", 
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Get monthly breakdown of unpaid fees (students)
    const monthlyUnpaidFees = await Fee.aggregate([
      { 
        $match: { 
          year: yearNum,
          $or: [{ paid: false }, { paid: 0 }, { paid: 'false' }] 
        } 
      },
      { 
        $group: { 
          _id: "$month", 
          total: { $sum: "$amount" },
          count: { $sum: 1 }
        } 
      },
      { $sort: { _id: 1 } }
    ]);

    // Create monthly breakdown
    const monthlyBreakdown = [];
    for (let month = 1; month <= 12; month++) {
      const feesData = monthlyFees.find(f => f._id === month) || { total: 0, count: 0 };
      const salariesData = monthlySalaryExpenses.find(s => s._id === month) || { total: 0, count: 0 };
      const paidSalariesData = monthlyPaidSalaries.find(s => s._id === month) || { count: 0 };
      const unpaidData = monthlyUnpaidFees.find(u => u._id === month) || { total: 0, count: 0 };

      monthlyBreakdown.push({
        month,
        income: feesData.total,
        expenses: salariesData.total,
        debt: unpaidData.total,
        paidFeesCount: feesData.count,
        paidSalariesCount: paidSalariesData.count,
        unpaidFeesCount: unpaidData.count,
        netProfit: feesData.total - salariesData.total
      });
    }

    return res.status(200).json({ 
      message: "Faahfaahinta maalgelinta sanadka si guul leh ayaa loo helay", 
      yearlyBreakdown: {
        year: yearNum,
        monthlyBreakdown,
        totalIncome: monthlyFees.reduce((sum, f) => sum + f.total, 0),
        totalExpenses: monthlySalaryExpenses.reduce((sum, s) => sum + s.total, 0),
        totalDebt: monthlyUnpaidFees.reduce((sum, u) => sum + u.total, 0),
        totalPaidFees: monthlyFees.reduce((sum, f) => sum + f.count, 0),
        totalPaidSalaries: monthlyPaidSalaries.reduce((sum, s) => sum + s.count, 0),
        totalUnpaidFees: monthlyUnpaidFees.reduce((sum, u) => sum + u.count, 0)
      }
    });
  } catch (error) {
    console.error("error in getYearlyFinanceBreakdown function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

export const getFinanceById = async ( req, res ) => {
  try {
    const { financeId } = req.params;

    const finance = await Finance.findById(financeId);

    if (!finance) {
      return res.status(404).json({ message: "Maalgelinta lama helin" });
    }

    return res.status(200).json({ message: "Maalgelinta si guul leh ayaa loo helay", finance });
  } catch (error) {
    console.error("error in getFinanceById function: ", error);
    return res.status(500).json({ message: error.message });
  }
}

