import React, { useEffect, useState } from 'react';
import { FiDollarSign, FiTrendingUp, FiTrendingDown, FiCreditCard, FiPlus, FiList, FiEye, FiCalendar, FiUsers, FiRefreshCw } from 'react-icons/fi';
import { Link } from 'react-router-dom';
import useFinanceStore from '../../store/financeStore';

const Finance = () => {
  const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [showMonthlyBreakdown, setShowMonthlyBreakdown] = useState(false);
  
  const { 
    finances, 
    financeSummary,
    yearlyBreakdown,
    loading, 
    getAllFinance, 
    getFinanceSummary,
    getYearlyFinanceBreakdown,
    generateMonthlyFinance,
    getTotalIncome, 
    getTotalExpenses, 
    getTotalDebt, 
    getNetProfit,
    getAutoGeneratedFinances,
    getManualFinances
  } = useFinanceStore();

  useEffect(() => {
    getAllFinance();
  }, [getAllFinance]);

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('so-SO', {
      style: 'currency',
      currency: 'SOS',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount || 0);
  };

  const formatDate = (date) => {
    return new Date(date).toLocaleDateString('so-SO');
  };

  const getMonthName = (monthNum) => {
    const months = [
      'january', 'February', 'March', 'April', 'May', 'Juun',
      'July', 'Agoosto', 'Sebtembar', 'Oktoobar', 'Nofembar', 'Diseembar'
    ];
    return months[monthNum - 1];
  };

  const handleGenerateMonthlyFinance = async () => {
    await generateMonthlyFinance(selectedMonth, selectedYear);
    getAllFinance(); // Refresh the list
  };

  const handleGetSummary = async () => {
    await getFinanceSummary(selectedMonth, selectedYear);
  };

  const handleGetYearlyBreakdown = async () => {
    await getYearlyFinanceBreakdown(selectedYear);
    setShowMonthlyBreakdown(true);
  };

  const totalIncome = getTotalIncome();
  const totalExpenses = getTotalExpenses();
  const totalDebt = getTotalDebt();
  const netProfit = getNetProfit();

  const recentFinances = finances.slice(0, 5);
  const autoGeneratedFinances = getAutoGeneratedFinances();
  const manualFinances = getManualFinances();

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-800 flex items-center">
            <FiDollarSign className="mr-3 text-green-600" />
            Maamulka Dhaqaalaha Sanadlaha
          </h1>
          <p className="text-gray-600 mt-2">
            Eeg iyo maamul dhaqaalaha iskuulka - Lacagta ardayda iyo mushaharka macalimiinta
          </p>
        </div>

        {/* Auto-Generate Monthly Finance Section */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-8">
          <h2 className="text-xl font-semibold text-gray-800 mb-4 flex items-center">
            <FiRefreshCw className="mr-2" />
            Si toos ah u abuur dhaqaalaha bishan
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Bisha</label>
              <select 
                value={selectedMonth} 
                onChange={(e) => setSelectedMonth(parseInt(e.target.value))}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                {Array.from({ length: 12 }, (_, i) => i + 1).map(month => (
                  <option key={month} value={month}>
                    {getMonthName(month)}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Sanadka</label>
              <select 
                value={selectedYear} 
                onChange={(e) => setSelectedYear(parseInt(e.target.value))}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                {Array.from({ length: 5 }, (_, i) => new Date().getFullYear() - 2 + i).map(year => (
                  <option key={year} value={year}>{year}</option>
                ))}
              </select>
            </div>
            <div className="flex items-end">
              <button
                onClick={handleGenerateMonthlyFinance}
                disabled={loading}
                className="w-full bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
              >
                {loading ? (
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                ) : (
                  <>
                    <FiRefreshCw className="mr-2" />
                    Abuur Dhaqaale
                  </>
                )}
              </button>
            </div>
            <div className="flex items-end">
              <button
                onClick={handleGetSummary}
                disabled={loading}
                className="w-full bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
              >
                <FiEye className="mr-2" />
                Eeg Faahfaahin
              </button>
            </div>
          </div>
          <p className="text-sm text-gray-600">
            Tani waxay si toos ah u xisaabin doontaa lacagta ardayda (dakhliga) iyo mushaharka macalimiinta (kharashka) bishan.
          </p>
        </div>

        {/* Statistics Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {/* Total Income */}
          <div className="bg-gradient-to-r from-green-500 to-green-600 rounded-lg shadow-lg p-6 text-white">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-green-100 text-sm font-medium">Wadarta Dakhliga</p>
                <p className="text-2xl font-bold">{formatCurrency(totalIncome)}</p>
                <p className="text-green-200 text-xs">Lacagta ardayda</p>
              </div>
              <FiTrendingUp className="text-3xl text-green-200" />
            </div>
          </div>

          {/* Total Expenses */}
          <div className="bg-gradient-to-r from-red-500 to-red-600 rounded-lg shadow-lg p-6 text-white">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-red-100 text-sm font-medium">Wadarta Kharashka</p>
                <p className="text-2xl font-bold">{formatCurrency(totalExpenses)}</p>
                <p className="text-red-200 text-xs">Mushaharka macalimiinta</p>
              </div>
              <FiTrendingDown className="text-3xl text-red-200" />
            </div>
          </div>

          {/* Total Debt */}
          <div className="bg-gradient-to-r from-orange-500 to-orange-600 rounded-lg shadow-lg p-6 text-white">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-orange-100 text-sm font-medium">Wadarta Qaansheega</p>
                <p className="text-2xl font-bold">{formatCurrency(totalDebt)}</p>
                <p className="text-orange-200 text-xs">Lacagta aan la bixin</p>
              </div>
              <FiCreditCard className="text-3xl text-orange-200" />
            </div>
          </div>

          {/* Net Profit */}
          <div className={`rounded-lg shadow-lg p-6 text-white ${
            netProfit >= 0 
              ? 'bg-gradient-to-r from-blue-500 to-blue-600' 
              : 'bg-gradient-to-r from-red-500 to-red-600'
          }`}>
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium opacity-90">Faahfaahin</p>
                <p className="text-2xl font-bold">{formatCurrency(netProfit)}</p>
                <p className="text-xs opacity-80">Dakhliga - Kharashka</p>
              </div>
              <FiDollarSign className="text-3xl opacity-80" />
            </div>
          </div>
        </div>

        {/* Finance Summary Display */}
        {financeSummary && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-8">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">
              Faahfaahinta Dhaqaalaha {getMonthName(financeSummary.month)} {financeSummary.year}
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="text-center">
                <p className="text-sm text-gray-600">Dakhliga (Lacagta Ardayda)</p>
                <p className="text-2xl font-bold text-green-600">{formatCurrency(financeSummary.income)}</p>
                <p className="text-sm text-gray-500">{financeSummary.paidFeesCount} arday oo bixiyay</p>
              </div>
              <div className="text-center">
                <p className="text-sm text-gray-600">Kharashka (Mushaharka Macalimiinta)</p>
                <p className="text-2xl font-bold text-red-600">{formatCurrency(financeSummary.expenses)}</p>
                <p className="text-sm text-gray-500">{financeSummary.paidSalariesCount} macallin oo la bixiyay</p>
              </div>
              <div className="text-center">
                <p className="text-sm text-gray-600">Qaansheega (Lacagta aan la bixin)</p>
                <p className="text-2xl font-bold text-orange-600">{formatCurrency(financeSummary.debt)}</p>
                <p className="text-sm text-gray-500">{financeSummary.unpaidFeesCount} arday oo aan bixin</p>
              </div>
            </div>
          </div>
        )}

        {/* Yearly Breakdown Button */}
        <div className="mb-8">
          <button
            onClick={handleGetYearlyBreakdown}
            disabled={loading}
            className="bg-purple-600 text-white px-6 py-3 rounded-md hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
          >
            <FiCalendar className="mr-2" />
            Eeg Faahfaahinta Sanadka {selectedYear}
          </button>
        </div>

        {/* Monthly Breakdown Chart */}
        {yearlyBreakdown && showMonthlyBreakdown && (
          <div className="bg-white rounded-lg shadow-md p-6 mb-8">
            <h3 className="text-lg font-semibold text-gray-800 mb-4">
              Faahfaahinta Dhaqaalaha Sanadka {yearlyBreakdown.year}
            </h3>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Bisha</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Dakhliga</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Kharashka</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Qaansheega</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Faahfaahin</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {yearlyBreakdown.monthlyBreakdown.map((month) => (
                    <tr key={month.month} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {getMonthName(month.month)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-green-600 font-semibold">
                        {formatCurrency(month.income)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-red-600 font-semibold">
                        {formatCurrency(month.expenses)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-orange-600 font-semibold">
                        {formatCurrency(month.debt)}
                      </td>
                      <td className={`px-6 py-4 whitespace-nowrap text-sm font-semibold ${
                        month.netProfit >= 0 ? 'text-green-600' : 'text-red-600'
                      }`}>
                        {formatCurrency(month.netProfit)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
              <div>
                <p className="text-sm text-gray-600">Wadarta Dakhliga</p>
                <p className="text-lg font-bold text-green-600">{formatCurrency(yearlyBreakdown.totalIncome)}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Wadarta Kharashka</p>
                <p className="text-lg font-bold text-red-600">{formatCurrency(yearlyBreakdown.totalExpenses)}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600">Wadarta Qaansheega</p>
                <p className="text-lg font-bold text-orange-600">{formatCurrency(yearlyBreakdown.totalDebt)}</p>
              </div>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-4 mb-8">
          <Link
            to="/finance/add"
            className="bg-blue-600 text-white px-6 py-3 rounded-md hover:bg-blue-700 flex items-center"
          >
            <FiPlus className="mr-2" />
            Ku dar Dhaqaale
          </Link>
          <Link
            to="/finance/getAll"
            className="bg-gray-600 text-white px-6 py-3 rounded-md hover:bg-gray-700 flex items-center"
          >
            <FiList className="mr-2" />
            Eeg Dhammaan
          </Link>
        </div>

        {/* Recent Finances */}
        <div className="bg-white rounded-lg shadow-md">
          <div className="px-6 py-4 border-b border-gray-200">
            <h3 className="text-lg font-semibold text-gray-800">Dhaqaalaha Dhowaan</h3>
          </div>
          <div className="overflow-x-auto">
            {loading ? (
              <div className="p-6 text-center">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
                <p className="mt-2 text-gray-600">Waa la soo dejiniyaa...</p>
              </div>
            ) : recentFinances.length === 0 ? (
              <div className="p-6 text-center">
                <FiDollarSign className="mx-auto h-12 w-12 text-gray-400" />
                <p className="mt-2 text-gray-600">Wali ma jiro dhaqaale</p>
                <Link
                  to="/finance/add"
                  className="mt-4 inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
                >
                  <FiPlus className="mr-2" />
                  Ku dar Dhaqaale
                </Link>
              </div>
            ) : (
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Taariikhda
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Dakhliga
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Kharashka
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Qaansheega
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Faahfaahin
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Tallaabooyin
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {recentFinances.map((finance) => {
                    const profit = (finance.income || 0) - (finance.expenses || 0);
                    return (
                      <tr key={finance._id} className="hover:bg-gray-50">
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                          {new Date(finance.date).toLocaleDateString('so-SO')}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-green-600 font-semibold">
                          {formatCurrency(finance.income)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-red-600 font-semibold">
                          {formatCurrency(finance.expenses)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm text-orange-600 font-semibold">
                          {formatCurrency(finance.debt)}
                        </td>
                        <td className={`px-6 py-4 whitespace-nowrap text-sm font-semibold ${
                          profit >= 0 ? 'text-green-600' : 'text-red-600'
                        }`}>
                          {formatCurrency(profit)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          <Link
                            to={`/finance/get/${finance._id}`}
                            className="text-blue-600 hover:text-blue-900 flex items-center"
                          >
                            <FiEye className="mr-1" />
                            Eeg
                          </Link>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            )}
          </div>
          {recentFinances.length > 0 && (
            <div className="px-6 py-4 border-t border-gray-200">
              <Link
                to="/finance/getAll"
                className="text-blue-600 hover:text-blue-900 text-sm font-medium flex items-center"
              >
                Eeg dhammaan maalgelinta
                <FiEye className="ml-1" />
              </Link>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Finance;