import mongoose from 'mongoose';

const financeSchema = new mongoose.Schema({
  date: { type: Date, default: Date.now },
  income: { type: Number, default: 0 },
  expenses: { type: Number, default: 0 },
  debt: { type: Number, default: 0 },
  month: { type: Number, required: true },
  year: { type: Number, required: true },
  isAutoGenerated: { type: Boolean, default: false },
  paidFeesCount: { type: Number, default: 0 },
  paidSalariesCount: { type: Number, default: 0 },
  unpaidFeesCount: { type: Number, default: 0 },
  lastUpdated: { type: Date, default: Date.now },
}, { timestamps: true });

export default mongoose.models.Finance || mongoose.model('Finance', financeSchema);
