import mongoose from "mongoose";

const FinanceSchema = mongoose.Schema({
  date: {
    type: Date,
    required: true,
    default: Date.now
  },
  income: {
    type: Number, 
    required: true,
    min: 0,
  },
  expenses: {
    type: Number,
    required: true,
    min: 0
  },
  debt: {
    type: Number,
    min: 0,
    required: true
  },
  // New fields for auto-generated monthly records
  month: {
    type: Number,
    min: 1,
    max: 12
  },
  year: {
    type: Number,
    min: 2000
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  paidFeesCount: {
    type: Number,
    default: 0
  },
  paidSalariesCount: {
    type: Number,
    default: 0
  },
  unpaidFeesCount: {
    type: Number,
    default: 0
  },
  lastUpdated: {
    type: Date,
    default: Date.now
  }
}, { timestamps: true });

const Finance = mongoose.model("Finance", FinanceSchema);

export default Finance;
